import {test,expect} from '../../../helpers/test';
import {login} from '../../../helpers/auth';
import {mkdir} from 'node:fs/promises';

test('@finance ACC-01 ACC-03 ACC-04 journal draft validates, posts and unposts with persisted details',async({page},info)=>{
  test.setTimeout(150_000);
  const reference=String(Date.now());
  const description=`FIN-E2E-POST-${reference}`;
  let id:string|undefined;
  await mkdir('artifacts/finance',{recursive:true});
  await login(page);
  try {
    await page.goto('/en/finance/accounting/journal-entries/create');
    await page.getByPlaceholder('MM/DD/YYYY',{exact:true}).fill(new Intl.DateTimeFormat('en-US',{month:'2-digit',day:'2-digit',year:'numeric',timeZone:'Africa/Cairo'}).format(new Date()));
    await page.locator('input[name=ref]').fill(reference);
    await page.locator('textarea[name=description]').fill(description);
    await expect(page.getByPlaceholder('Currency',{exact:true})).toHaveValue('SAR');
    await page.getByPlaceholder('Search by name, number, or type').fill('cash');
    await page.getByRole('option').filter({hasText:/Main treasury\s*#1111001/}).click();
    await page.getByRole('button',{name:'New',exact:true}).click();
    await page.getByPlaceholder('Search by name, number, or type').nth(1).click();
    await page.getByRole('option').filter({hasText:/Petty Cash\s*#1111002/}).click();
    await page.locator('input[name=debit_0]').fill('0.10');
    await page.locator('input[name=credit_1]').fill('0.10');
    await page.getByRole('button',{name:'Submit',exact:true}).click();
    const created=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/finance/journal_entries'));
    await page.getByRole('menuitem',{name:'Draft',exact:true}).click();
    const response=await created;
    expect(response.ok()).toBeTruthy();
    id=(await response.json()).data.id;
    expect(id).toBeTruthy();
    await info.attach('test-journal-identity',{body:JSON.stringify({id,reference,description}),contentType:'application/json'});
    await expect(page.getByRole('row').filter({hasText:description})).toContainText('Draft');
    await page.goto(`/en/finance/accounting/journal-entries/edit/${id}`);
    await expect(page.locator('textarea[name=description]')).toHaveValue(description);
    await expect(page.locator('input[name=debit_0]')).toHaveValue(/0\.1(?:0)?/);
    await expect(page.locator('input[name=credit_1]')).toHaveValue(/0\.1(?:0)?/);
    await page.getByRole('button',{name:'Save',exact:true}).click();
    const posted=page.waitForResponse(r=>['POST','PUT','PATCH'].includes(r.request().method())&&r.url().includes('/finance/journal_entries'));
    await page.getByRole('menuitem',{name:'Validate',exact:true}).click();
    const result=await posted;
    await info.attach('posting-response',{body:await result.text(),contentType:'application/json'});
    expect(result.ok(),'Validate request succeeds').toBeTruthy();
    await page.goto(`/en/finance/accounting/journal-entries/edit/${id}`);
    await expect(page.getByRole('main')).toContainText('Unposted');
    const posting=page.waitForResponse(r=>['POST','PUT','PATCH'].includes(r.request().method())&&r.url().includes('/finance/journal_entries'));
    await page.getByRole('button',{name:'Post',exact:true}).click();
    const postingResult=await posting;
    await info.attach('post-response',{body:await postingResult.text(),contentType:'application/json'});
    expect(postingResult.ok(),'Post request succeeds').toBeTruthy();
    await page.reload();
    await expect(page.getByRole('main').getByText('Posted',{exact:true})).toBeVisible();
    await page.screenshot({path:'artifacts/finance/journal-posted.png',fullPage:true});
    await info.attach('posted-screen',{path:'artifacts/finance/journal-posted.png',contentType:'image/png'});
    await page.goto(`/en/finance/accounting/journal-entries/edit/${id}`);
    await expect(page.locator('textarea[name=description]')).toHaveValue(description);
    await page.getByRole('button',{name:'Unpost',exact:true}).click();
    const dialog=page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    const unposting=page.waitForResponse(r=>['POST','PUT','PATCH'].includes(r.request().method())&&r.url().includes('/finance/journal_entries'));
    await dialog.getByRole('button',{name:'Confirm Unpost',exact:true}).click();
    const unpostedResponse=await unposting;
    await info.attach('unpost-response',{body:await unpostedResponse.text(),contentType:'application/json'});
    expect(unpostedResponse.ok()).toBeTruthy();
    await page.reload();
    // User-confirmed lifecycle: Unpost returns to Unposted, not Draft.
    await expect(page.getByRole('main').getByText('Unposted',{exact:true})).toBeVisible();
    await expect(page.locator('input[name=ref]')).toHaveValue(reference);
    await expect(page.locator('textarea[name=description]')).toHaveValue(description);
    await expect(page.locator('input[name=debit_0]')).toHaveValue(/0\.1(?:0)?/);
    await expect(page.locator('input[name=credit_1]')).toHaveValue(/0\.1(?:0)?/);
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    await page.getByRole('dialog').getByRole('button',{name:'Go Back',exact:true}).click();
    await expect(page.getByRole('main').getByText('Unposted',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    const cancelResponse=page.waitForResponse(r=>['POST','PUT','PATCH'].includes(r.request().method())&&r.url().includes('/finance/journal_entries'));
    await page.getByRole('dialog').getByRole('button',{name:'Confirm Cancel',exact:true}).click();
    const canceled=await cancelResponse;
    await info.attach('cancel-response',{body:await canceled.text(),contentType:'application/json'});
    expect(canceled.ok()).toBeTruthy();
    await page.reload();
    await expect(page.getByRole('main').getByText('Canceled',{exact:true})).toBeVisible();
    await expect(page.getByRole('button',{name:'Post',exact:true})).toBeHidden();
  }finally{
    await page.screenshot({path:'artifacts/finance/journal-posting-final.png',fullPage:true});
    await info.attach('posting-final',{path:'artifacts/finance/journal-posting-final.png',contentType:'image/png'});
    await info.attach('retained-test-record',{body:JSON.stringify({id,reference,description,note:'Retained for audit and reversal testing; do not delete unrelated records.'}),contentType:'application/json'});
  }
});
